name: Setup Vlang Environment

description: 'Installs Vlang with a specific version in the user-defined path using Bash'

author: 'siguici'

branding:
  icon: download
  color: blue

inputs:
  path:
    description: 'The destination path for V'
    default: '${{ runner.temp }}/v'
    required: false

  update:
    description: 'Update V after installation'
    default: 'false'
    required: false

  install:
    description: 'Install V dependencies'
    default: 'false'
    required: false

  cwd:
    description: 'Current working directory for commands'
    required: false
    default: '.'

  token:
    description: 'Personal Access Token (PAT) for fetching the repository'
    default: '${{ github.token }}'
    required: false

  version:
    description: 'Version of V to install (branch, tag, SHA)'
    default: ''
    required: false

  version-file:
    description: 'File containing the version to use'
    default: ''
    required: false

  latest:
    description: 'Check for the latest available version'
    default: 'false'
    required: false

  stable:
    description: 'Use the latest stable version'
    default: 'false'
    required: false

  architecture:
    description: 'Target architecture (linux, macos, windows)'
    default: ''
    required: false

outputs:
  bin-path:
    description: 'Path to the directory containing V binary'
    value: '${{ inputs.path }}'

  v-bin-path:
    description: 'Path to the V binary'
    value: '${{ inputs.path }}/v'

  version:
    description: 'Installed version of V'
    value: '${{ steps.get-version.outputs.version }}'

  architecture:
    description: 'System architecture used'
    value: '${{ runner.os }}'

runs:
  using: 'composite'
  steps:
    - name: 🛠️ Prepare the environment
      uses: siguici/setup-env@v0
      with:
        packages: 'git gh jq'

    - name: 📌 Determine Vlang Version
      id: determine-version
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: |
        VERSION="${{ inputs.version || 'latest' }}"
        echo "VERSION=$VERSION" >> "$GITHUB_ENV"

    - name: 📥 Install Vlang on Unix
      shell: bash
      if: runner.os != 'Windows'
      run: |
        chmod +x install.sh
        ./install.sh --dir "${{ inputs.path }}" --version "$VERSION"

    - name: 📥 Install Vlang on Windows
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        .\install.ps1 -installDir "${{ inputs.path }}" -version $env:VERSION

    - name: 🔄 Update V if required
      shell: bash
      if: ${{ inputs.update == 'true' && env.V_VERSION != 'latest' }}
      run: |
        if v help | grep -q "up"; then
          v up
        else
          echo "⚠️ \`v up\` not available on this version, ignored."
        fi

    - name: 📦 Install V dependencies
      shell: bash
      if: ${{ inputs.install == 'true' }}
      working-directory: ${{ inputs.cwd }}
      run: |
        v install

    - name: 🔍 Detect Architecture
      id: detect-arch
      shell: bash
      run: |
        ARCH="${{ inputs.architecture }}"
        if [[ -z "$ARCH" ]]; then
          case "$(uname -m)" in
            x86_64) ARCH="amd64" ;;
            aarch64) ARCH="arm64" ;;
            *) ARCH="unknown" ;;
          esac
        fi
        echo "ARCH=$ARCH" >> "$GITHUB_ENV"

    - name: 🔍 Get installed V version
      id: get-version
      shell: bash
      run: echo "version=$(v -version)" >> "$GITHUB_OUTPUT"
