name: Setup Vlang Environment

description: 'Installs Vlang with a specific version in the user-defined path using Bash'

author: 'siguici'

branding:
  icon: download
  color: blue

inputs:
  path:
    description: 'The destination path for V'
    default: '${{ runner.temp }}/v'
    required: false

  install:
    description: 'Install V dependencies'
    default: 'false'
    required: false

  cwd:
    description: 'Current working directory for commands'
    required: false
    default: '.'

  token:
    description: 'Personal Access Token (PAT) for fetching the repository'
    default: '${{ github.token }}'
    required: false

  version:
    description: 'Version of V to install (branch, tag, SHA)'
    default: ''
    required: false

  version-file:
    description: 'File containing the version to use'
    default: ''
    required: false

  check-latest:
    description: 'Check for the latest available version'
    default: 'false'
    required: false

  stable:
    description: 'Use the latest stable version'
    default: 'false'
    required: false

  architecture:
    description: 'Target architecture (linux, macos, windows)'
    default: ''
    required: false

outputs:
  bin-path:
    description: 'Path to the directory containing V binary'
    value: '${{ inputs.path }}'

  v-bin-path:
    description: 'Path to the V binary'
    value: '${{ inputs.path }}/v'

  version:
    description: 'Installed version of V'
    value: '${{ steps.get-version.outputs.version }}'

  architecture:
    description: 'System architecture used'
    value: '${{ runner.os }}'

runs:
  using: 'composite'
  steps:
    - name: 🛠️ Prepare the environment
      uses: siguici/setup-env@v0
      with:
        packages: 'git'

    - name: 📥 Clone Vlang repository
      shell: bash
      run: |
        mkdir -p "${{ inputs.path }}"
        git clone https://github.com/vlang/v "${{ inputs.path }}"
        cd "${{ inputs.path }}"
        if [[ -n "${{ inputs.version }}" ]]; then
          git checkout "${{ inputs.version }}"
        fi

    - name: 🏗️ Build & Install Vlang on Unix
      shell: bash
      if: runner.os != 'Windows'
      run: |
        cd "${{ inputs.path }}"
        make
        ./v symlink

    - name: 🏗️ Build & Install Vlang on Windows
      shell: bash
      if: runner.os == 'Windows'
      run: |
        cd "${{ inputs.path }}"
        ./make.bat
        v.exe symlink

    - name: 📦 Install V dependencies
      shell: bash
      if: inputs.install == "true"
      working-directory: ${{ inputs.cwd }}
      run: |
        v install

    - name: 🔍 Get installed V version
      id: get-version
      shell: bash
      run: echo "version=$(v -version)" >> "$GITHUB_OUTPUT"
