name: Test

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        experimental: [true]
    name: 👷 CI Vlang on ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Vlang Environment
        uses: ./
        with:
          version-file: './.v-version'
          install: true
          cwd: ./lab
          latest: true
          stable: true
          update: true
